version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: hub.Dockerfile
    ports:
      - "5173:5173"  # Map host port 5173 to container port 5173 for Vite dev server
    volumes:
      - C:/Users/fire/Documents/Code/web/academic-hub/frontend:/app
      - /app/node_modules  # Anonymous volume to prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0  # Override command to run dev server
    depends_on:
      - api
    networks:
      - a-hub-net

  # Backend API service
  api:
    build:
      context: ./backend/api
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - C:/Users/fire/Documents/Code/web/academic-hub/backend/api:/app
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_OWNER_ADMIN=${POSTGRES_USER}
      - DB_OWNER_PWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - a-hub-net

  # Database service
  db:
    build:
      context: ./backend/db
      dockerfile: db.Dockerfile
    volumes:
      - a-hub-dt:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PASSWORD_INFRASTRUCTURE=${PASSWORD_INFRASTRUCTURE}
      - PASSWORD_HR=${PASSWORD_HR}
      - PASSWORD_ACADEMIC=${PASSWORD_ACADEMIC}
      - PASSWORD_COURSE_OFFERING=${PASSWORD_COURSE_OFFERING}
      - PASSWORD_STUDENT=${PASSWORD_STUDENT}
      - PASSWORD_LIBRARY=${PASSWORD_LIBRARY}
    networks:
      - a-hub-net

networks:
  a-hub-net:

volumes:
  a-hub-dt:
